backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: candidates
    label: "Candidates"
    folder: "content/english/candidates"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - label: Image
        name: image
        widget: image
        media_library:
          config:
            multiple: false
      - {label: "Background Image", name: bg_image, widget: hidden, default: "images/background-oakland-panorama.jpg"}
      - {label: Description, name: description, hint: "Example: 'Candidate for City Council - District 1'", widget: string}
      - {label: Position, name: appointments, widget: string}
      - {label: Bio, name: bio, widget: string}
      - {label: Tags, hint: "Comma separated list", name: tags, widget: list }
      - label: Contact
        name: contact
        widget: list
        fields:
          - {label: Name, hint: "Example: 'Official Twitter'", name: name, widget: string}
          - {label: Icon, hint: "Example: 'ti-twitter-alt'", name: icon, widget: string}
          - {label: Link, hint: "Example: 'https://twitter.com/astropuffin'", name: link, widget: string}
      - {label: "Content Type", name: "type", widget: "string", default: "candidates"}
      - {label: "Body", name: "body", widget: "markdown"}
    filter:
      field: type
      value: candidates

