backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: candidate
    label: "Candidate"
    folder: "content/english/candidates"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - label: Image
        name: image
        hint: "Should be a square image with equal hight and width."
        widget: image
        media_library:
          config:
            multiple: false
      - {label: "Background Image", name: bg_image, widget: hidden, default: "images/background-oakland-panorama.jpg"}
      - {label: "draft", name: draft, widget: hidden, default: false}
      - {label: Description, name: description, hint: "Example: 'Candidate for City Council - District 1'", widget: string}
      - {label: Position, name: appointments, widget: string}
      - {label: Bio, name: bio, widget: string}
      - {label: Tags, hint: "Comma separated list", name: tags, widget: list }
      - label: Contact
        name: contact
        widget: list
        fields:
          - {label: Name, hint: "Example: 'Official Twitter'", name: name, widget: string}
          - {label: Icon, hint: "List of options: https://themify.me/themify-icons", name: icon, widget: string}
          - {label: Link, hint: "Example: 'https://twitter.com/astropuffin'", name: link, widget: string}
      - {label: "Content Type", name: "type", widget: "hidden", default: "candidates"}
      - label: "SEO Tags"
        name: seoTags
        widget: list
        required: false
        fields:
          - {label: Name, hint: "Name of the meta tag", name: name, widget: string}
          - {label: Content, hint: "Content for the meta tag", name: content, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
    filter:
      field: type
      value: candidates
  - name: guide_district
    label: "District"
    folder: "content/english/guide"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: "Background Image", name: bg_image, widget: hidden, default: "images/background-oakland-panorama.jpg"}
      - {label: Description, name: description, hint: "Example: 'Temescal, hills through Montclair'", widget: string}
      - label: Image
        name: image
        widget: image
        media_library:
          config:
            multiple: false
      - {label: "Content Type", name: "type", widget: "hidden", default: "guide"}
      - label: "SEO Tags"
        name: seoTags
        widget: list
        required: false
        fields:
          - {label: Name, hint: "Name of the meta tag", name: name, widget: string}
          - {label: Content, hint: "Content for the meta tag", name: content, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
    filter:
      field: type
      value: guide
  - name: guide_index
    label: "Guide Main Page"
    folder: "content/english/guide"
    create: false
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Byline, name: byline, widget: string}
      - {label: "Background Image", name: bg_image, widget: hidden, default: "images/OaklandPanorama2.jpg"}
      - {label: Description, name: description, widget: string}
      - {label: "Content Type", name: "type", widget: "hidden", default: "guide_index"}
      - label: Buttons
        name: buttons
        widget: list
        fields:
          - {label: title, name: title, widget: string}
          - {label: link, name: link, widget: string}
      - label: "SEO Tags"
        name: seoTags
        widget: list
        required: false
        fields:
          - {label: Name, hint: "Name of the meta tag", name: name, widget: string}
          - {label: Content, hint: "Content for the meta tag", name: content, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
    filter:
      field: type
      value: guide_index
  - name: how_to_vote
    label: "How to Vote"
    folder: "content/english/how-to-vote"
    create: false
    fields:
      - {label: Title, name: title, widget: string}
      - {label: "Background Image", name: bg_image, widget: hidden, default: "images/OaklandPanorama2.jpg"}
      - {label: Description, name: description, widget: string}
      - {label: "Content Type", name: "type", widget: "hidden", default: "how_to_vote_index"}
      - label: "SEO Tags"
        name: seoTags
        widget: list
        required: false
        fields:
          - {label: Name, hint: "Name of the meta tag", name: name, widget: string}
          - {label: Content, hint: "Content for the meta tag", name: content, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
    filter:
      field: type
      value: how_to_vote_index
  - name: methodology
    label: "Methodology"
    folder: "content/english/methodology"
    create: false
    fields:
      - {label: Title, name: title, widget: string}
      - {label: "Background Image", name: bg_image, widget: hidden, default: "images/OaklandPanorama2.jpg"}
      - {label: Description, name: description, widget: string}
      - {label: "Content Type", name: "type", widget: "hidden", default: "methodology_index"}
      - label: "SEO Tags"
        name: seoTags
        widget: list
        required: false
        fields:
          - {label: Name, hint: "Name of the meta tag", name: name, widget: string}
          - {label: Content, hint: "Content for the meta tag", name: content, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
    filter:
      field: type
      value: methodology_index
  - name: about
    label: "About"
    folder: "content/english/about"
    create: false
    fields:
      - {label: Title, name: title, widget: string}
      - {label: "Background Image", name: bg_image, widget: hidden, default: "images/OaklandPanorama2.jpg"}
      - label: Image
        name: image
        widget: image
        defaut: "images/oakland_skyline_lake_merritt.jpg"
        media_library:
          config:
            multiple: false
      - {label: Description, name: description, widget: string}
      - {label: "Content Type", name: "type", widget: "hidden", default: "about_index"}
      - label: "SEO Tags"
        name: seoTags
        widget: list
        required: false
        fields:
          - {label: Name, hint: "Name of the meta tag", name: name, widget: string}
          - {label: Content, hint: "Content for the meta tag", name: content, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
    filter:
      field: type
      value: about_index


  - name: ballot_measure_index
    label: "Ballot Measures Main Page"
    folder: "content/english/ballot-measures"
    create: false
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Byline, name: byline, widget: string}
      - {label: "Background Image", name: bg_image, widget: hidden, default: "images/OaklandPanorama2.jpg"}
      - {label: Description, name: description, widget: string}
      - {label: "Content Type", name: "type", widget: "hidden", default: "ballot_measure_index"}
      - label: Buttons
        name: buttons
        widget: list
        fields:
          - {label: title, name: title, widget: string}
          - {label: link, name: link, widget: string}
      - label: "SEO Tags"
        name: seoTags
        widget: list
        required: false
        fields:
          - {label: Name, hint: "Name of the meta tag", name: name, widget: string}
          - {label: Content, hint: "Content for the meta tag", name: content, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
    filter:
      field: type
      value: ballot_measure_index
  - name: ballot_measure
    label: "Ballot Measures"
    folder: "content/english/ballot-measures"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: "Background Image", name: bg_image, widget: hidden, default: "images/background-oakland-panorama.jpg"}
      - {label: Description, name: description, widget: string}
      - {label: "Content Type", name: "type", widget: "hidden", default: "guide"}
      - label: "SEO Tags"
        name: seoTags
        widget: list
        required: false
        fields:
          - {label: Name, hint: "Name of the meta tag", name: name, widget: string}
          - {label: Content, hint: "Content for the meta tag", name: content, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
    filter:
      field: type
      value: ballot_measure
